# -*- coding: utf-8 -*-
"""一次性脚本：写入 1914.fun 社区卡牌数据"""
import json

cards = [
 dict(id="charron_1906", name="Charron 1906 型轮式装甲车", nation="french_empire", unit_class="tank", cost_g=36, cost_z=3, attack=2, defense=3, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["响应"], rarity="common", effect_text="部署时压制 1 个敌方单位。", triggers={"on_deploy": {"actions": [{"op": "suppress", "count": 1}]}}),
 dict(id="charron_m1905", name="Charron M1905 装甲车", nation="french_empire", unit_class="tank", cost_g=30, cost_z=2, attack=1, defense=2, vision_range="adjacent_8", attack_range="adjacent_8", rarity="common", effect_text="部署：开发一张「Charron G10 M 装甲车」，使其全卡数值 -1。", triggers={"on_deploy": {"actions": [{"op": "add_to_hand", "card_id": "charron_g10_m", "count": 1}, {"op": "modify_card", "card_id": "charron_g10_m", "atk": -1, "def": -1}]}}),
 dict(id="charron_g10", name="Charron G10 装甲车", nation="french_empire", unit_class="tank", cost_g=68, cost_z=3, attack=2, defense=3, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["突击", "响应"], rarity="silver", effect_text="部署：友方场上所有具有「响应」的单位获得 +1/+2。", triggers={"on_deploy": {"actions": [{"op": "buff", "scope": "friendly_field", "filter": {"ability": "响应"}, "atk": 1, "def": 2}]}}),
 dict(id="kaiser_wilhelm_cannon", name="威廉皇帝炮（巴黎巨炮）", nation="german_empire", unit_class="artillery", cost_g=148, cost_z=6, attack=4, defense=5, vision_range="global", attack_range="global", abilities=["坚守2", "修复3", "潜行"], rarity="silver", effect_text="一回合一次，攻击敌方陆军时将其压制，并使敌方失去 54 点生产费用。", triggers={"on_damage_dealt": {"once_per_turn": True, "actions": [{"op": "suppress", "count": 1}, {"op": "economy", "who": "enemy", "amount": -54}]}}),
 dict(id="british_aid_convoy", name="大英援俄装甲力量", type="order", nation="british_empire", cost_g=0, cost_k=9, rarity="silver", effect_text="将 6 张「劳斯莱斯装甲车 1914 型」加入底线、手牌与商店，使其全卡数值 -1。", triggers={"on_play": {"actions": [{"op": "modify_card", "card_id": "rolls_royce_1914", "atk": -1, "def": -1}, {"op": "spawn", "card_id": "rolls_royce_1914", "count": 6, "where": "rear_line"}, {"op": "add_to_hand", "card_id": "rolls_royce_1914", "count": 6}, {"op": "spawn", "card_id": "rolls_royce_1914", "count": 6, "where": "shop"}]}}),
 dict(id="aussie_armored_car", name="澳大利亚一号装甲车", nation="british_empire", unit_class="tank", cost_g=24, cost_z=1, attack=0, defense=2, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["潜行"], passives=["cannot_attack"], rarity="gold", effect_text="无法攻击。（油费减免效果依赖油费系统，暂缓）"),
 dict(id="minerva_1914", name="比利时密涅瓦装甲车 1914 型", nation="neutral", unit_class="tank", cost_g=28, cost_z=2, attack=2, defense=2, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["冲锋", "响应", "潜行"], rarity="common", effect_text="部署：压制一个单位。亡计：若敌方主国为德国，友方失去 24 点生产费用。", triggers={"on_deploy": {"actions": [{"op": "suppress", "count": 1}]}, "on_death": {"filter": {"enemy_nation": "german_empire"}, "actions": [{"op": "economy", "who": "self", "amount": -24}]}}),
 dict(id="rolls_royce_1914", name="劳斯莱斯装甲车 1914 型", nation="british_empire", unit_class="tank", cost_g=66, cost_z=3, attack=2, defense=4, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["突击", "冲锋", "响应"], rarity="silver", effect_text="使敌方单位受伤时，揭示 1 个敌方潜行单位并使其 -1/-1。", triggers={"on_damage_dealt": {"actions": [{"op": "reveal_stealth", "count": 1}, {"op": "debuff_target", "atk": -1, "def": -1}]}}),
 dict(id="zheffre_putilov_1916", name="杰弗里-普季洛夫 1916", nation="russian_empire", unit_class="tank", cost_g=88, cost_z=5, attack=4, defense=5, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["守护"], rarity="common", effect_text="造成伤害时随机获得 +1/+1 或 -1/-2。", triggers={"on_damage_dealt": {"actions": [{"op": "random", "branches": [{"weight": 1, "actions": [{"op": "buff", "scope": "self", "atk": 1, "def": 1}]}, {"weight": 1, "actions": [{"op": "buff", "scope": "self", "atk": -1, "def": -2}]}], "salt": "zheffre"}]}}),
 dict(id="charron_g10_m", name="Charron G10 M 装甲车", nation="french_empire", unit_class="tank", cost_g=24, cost_z=2, attack=1, defense=3, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["突击", "响应"], passives=["damage_bonus_vs_suppressed:3"], rarity="silver", effect_text="本单位及相邻友方对被压制敌方单位的伤害 +3。"),
 dict(id="ehrhardt_ev4", name="Ehrhardt EV/4 型装甲车", nation="german_empire", unit_class="tank", cost_g=36, cost_z=3, attack=3, defense=4, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["守护", "响应", "修复2"], rarity="silver", effect_text="敌方指向受守护的友方时，友方获得 48 点生产费用。", triggers={"on_guarded_ally_attacked": {"actions": [{"op": "economy", "who": "self", "amount": 48}]}}),
 dict(id="bussing_a5p", name="布辛 A5P 机枪装甲车", nation="german_empire", unit_class="tank", cost_g=32, cost_z=3, attack=2, defense=5, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["守护", "响应", "修复2"], rarity="silver", effect_text="亡计：转化为德国步兵并获得 +2/+1。", triggers={"on_death": {"actions": [{"op": "transform", "to": "infantry_01"}, {"op": "buff", "scope": "self", "atk": 2, "def": 1}]}}),
 dict(id="zeppelin_l30", name="齐柏林 L30 飞艇（LZ 62）", nation="german_empire", unit_class="bomber", cost_g=72, cost_z=6, attack=3, defense=4, vision_range="front_3x2", attack_range="column_and_neighbors", rarity="silver", effect_text="攻击时随机消灭一个生产费用不大于 84 的敌方单位。", triggers={"on_damage_dealt": {"actions": [{"op": "destroy_random", "max_cost": 84}]}}),
 dict(id="zeppelin_lz4", name="齐柏林 LZ 4 飞艇", nation="german_empire", unit_class="bomber", cost_g=100, cost_z=2, attack=0, defense=3, vision_range="front_3x2", attack_range="column_and_neighbors", abilities=["响应"], rarity="common", effect_text="部署：生产「齐柏林飞艇」；亡计获得 164 点生产费用。", triggers={"on_deploy": {"actions": [{"op": "spawn", "card_id": "zeppelin_proto", "count": 1, "where": "shop"}]}, "on_death": {"actions": [{"op": "economy", "who": "self", "amount": 164}]}}),
 dict(id="gota_g3", name="戈塔 G.III", nation="german_empire", unit_class="bomber", cost_g=96, cost_z=3, attack=3, defense=2, vision_range="front_3x2", attack_range="column_and_neighbors", rarity="common", effect_text="亡计：转化为「戈塔 G.IV」。", triggers={"on_death": {"actions": [{"op": "transform", "to": "gota_g4"}]}}),
 dict(id="zeppelin_l4", name="齐柏林 L4 飞艇（LZ 27）", nation="german_empire", unit_class="bomber", cost_g=52, cost_z=1, attack=1, defense=2, vision_range="front_3x2", attack_range="column_and_neighbors", rarity="common", effect_text="亡计：商店中的本单位转化为「齐柏林 L11 飞艇（LZ 48）」。", triggers={"on_death": {"actions": [{"op": "shop_transform", "from_card": "zeppelin_l4", "to_card": "zeppelin_l11"}]}}),
 dict(id="zeppelin_l2", name="齐柏林 L2 飞艇（LZ 18）", nation="german_empire", unit_class="bomber", cost_g=100, cost_z=2, attack=1, defense=3, vision_range="front_3x2", attack_range="column_and_neighbors", rarity="common", effect_text="亡计：生产一张「齐柏林飞艇」。", triggers={"on_death": {"actions": [{"op": "spawn", "card_id": "zeppelin_proto", "count": 1, "where": "shop"}]}}),
 dict(id="defend_skies", name="保卫领空", type="order", nation="british_empire", cost_g=0, cost_k=5, rarity="gold", effect_text="使 2 架英国战斗机进入底线支援，结束本回合。", triggers={"on_play": {"end_turn_after": True, "actions": [{"op": "spawn", "card_id": "fighter_02", "count": 2, "where": "rear_line"}]}}),
 dict(id="zeppelin_l11", name="齐柏林 L11 飞艇（LZ 48）", nation="german_empire", unit_class="bomber", cost_g=196, cost_z=4, attack=3, defense=4, vision_range="front_3x2", attack_range="column_and_neighbors", rarity="silver", effect_text="部署：场上每有一个友方齐柏林，敌方失去 25 经济（上限 8 次）。", triggers={"on_deploy": {"actions": [{"op": "economy_per_friendly", "filter": {"card_id_prefix": "zeppelin"}, "per": 25, "cap": 8}]}}),
 dict(id="zeppelin_l70", name="齐柏林 L70 飞艇（LZ 112）", nation="german_empire", unit_class="bomber", cost_g=244, cost_z=10, attack=5, defense=5, vision_range="global", attack_range="global", passives=["cannot_be_attacked_by:fighter"], rarity="gold", effect_text="无法被战斗机攻击。友方失去战线时，压制该战线所有敌方单位并消灭本单位。", triggers={"on_line_lost": {"actions": [{"op": "suppress", "count": 9}, {"op": "destroy_self"}]}}),
 dict(id="zeppelin_lz3", name="齐柏林 LZ 3 飞艇（Z1）", nation="german_empire", unit_class="bomber", cost_g=124, cost_z=3, attack=2, defense=3, vision_range="front_3x2", attack_range="column_and_neighbors", rarity="gold", effect_text="商店中的德国轰炸机获得 +1/+1。", triggers={"on_deploy": {"actions": [{"op": "shop_buff", "filter": {"nation": "german_empire", "unit_class": "bomber"}, "atk": 1, "def": 1}]}}),
 dict(id="zeppelin_l44", name="齐柏林 L44 飞艇（LZ 74）", nation="german_empire", unit_class="bomber", cost_g=192, cost_z=7, attack=4, defense=4, vision_range="front_3x2", attack_range="column_and_neighbors", passives=["taunt"], rarity="silver", effect_text="敌方只能优先攻击本单位（嘲讽）。"),
 dict(id="bavarian_reserve_16", name="第 16 巴伐利亚后备团", nation="german_empire", unit_class="infantry", cost_g=24, cost_z=2, attack=2, defense=3, vision_range="adjacent_4", attack_range="adjacent_8", abilities=["突击", "响应"], rarity="common", effect_text="友方奥匈单位部署时，将一张「铁十字勋章」加入手牌。", triggers={"on_friendly_deploy": {"filter": {"nation": "austro_hungarian"}, "actions": [{"op": "add_to_hand", "card_id": "iron_cross", "count": 1}]}}),
 dict(id="gota_g2_proto", name="戈塔 G.II 原型机", nation="german_empire", unit_class="bomber", cost_g=60, cost_z=3, attack=2, defense=2, vision_range="front_3x2", attack_range="column_and_neighbors", abilities=["突击", "响应"], rarity="silver", effect_text="部署：开发一张戈塔 G 系列轰炸机。", triggers={"on_deploy": {"actions": [{"op": "add_to_hand", "card_id": "gota_g4", "count": 1}]}}),
 dict(id="gota_g4", name="戈塔 G.IV", nation="german_empire", unit_class="bomber", cost_g=112, cost_z=5, attack=4, defense=4, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["响应", "防空"], rarity="gold", effect_text="本单位攻击时，敌方失去 44 点经济。", triggers={"on_damage_dealt": {"actions": [{"op": "economy", "who": "enemy", "amount": -44}]}}),
 dict(id="kosmat_mortar_380", name="380mm 柯斯达迫击炮", nation="german_empire", unit_class="artillery", cost_g=148, cost_z=5, attack=4, defense=4, vision_range="adjacent_8", attack_range="global", abilities=["响应"], passives=["ignore_fort"], rarity="silver", effect_text="无视「工事」；压制被其攻击目标左右两格内的单位。", triggers={"on_damage_dealt": {"actions": [{"op": "suppress_area"}]}}),
 dict(id="big_bertha_420", name="大贝莎 420mm 重型榴弹炮", nation="german_empire", unit_class="artillery", cost_g=212, cost_z=8, attack=6, defense=6, vision_range="adjacent_8", attack_range="global", abilities=["坚守2", "响应"], passives=["ignore_fort"], rarity="gold", effect_text="无视「工事」。"),
 dict(id="a7v_main", name="A7V-主战型", nation="german_empire", unit_class="tank", cost_g=184, cost_z=6, attack=5, defense=7, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["坚守2", "冲锋"], rarity="silver", effect_text="对敌方单位造成伤害时，随机使一个敌方单位撤退。", triggers={"on_damage_dealt": {"actions": [{"op": "retreat_random"}]}}),
 dict(id="a7v_transport", name="A7V-R 运输型", nation="german_empire", unit_class="tank", cost_g=172, cost_z=6, attack=3, defense=5, vision_range="adjacent_8", attack_range="adjacent_8", abilities=["坚守2", "守护"], rarity="silver", effect_text="进入一条战线时，在该线加入 2 个步兵。", triggers={"on_enter_line": {"actions": [{"op": "spawn_adjacent", "card_id": "infantry_01", "count": 2}]}}),
 dict(id="iron_cross", name="铁十字勋章", type="order", nation="german_empire", cost_g=0, cost_k=1, rarity="common", effect_text="荣誉勋章（配套卡牌）。", triggers={"on_play": {"actions": []}}),
 dict(id="zeppelin_proto", name="齐柏林飞艇", nation="german_empire", unit_class="bomber", cost_g=80, cost_z=3, attack=2, defense=2, vision_range="front_3x2", attack_range="column_and_neighbors", rarity="common", effect_text="德意志飞艇部队的标准舰。"),
]

count = 0
for c in cards:
    c.setdefault("type", "unit")
    c.setdefault("nation", "neutral")
    c.setdefault("abilities", [])
    c["flavor_text"] = "1914.fun 社区卡牌"
    if c["type"] == "order":
        fname = "data/cards/orders/%s.json" % c["id"]
    else:
        fname = "data/cards/units/%s.json" % c["id"]
    with open(fname, "w", encoding="utf-8") as f:
        json.dump(c, f, ensure_ascii=False, indent=2)
    count += 1
print("written", count, "cards")
